export const GET_ERRORS ='GET_ERRORS';
export const SET_CURRENT_USER ='SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_DASHBOARD_DETAILS ='GET_DASHBOARD_DETAILS';
export const GET_USERGROUP_DETAILS ='GET_USERGROUP_DETAILS';
export const DASHBOARD_LOADING ='DASHBOARD_LOADING';
export const CLEAR_DASHBOARD_DETAILS ='CLEAR_DASHBOARD_DETAILS';

export const GET_EXPENSES ='GET_EXPENSES';
export const EXPENSE_LOADING ='EXPENSE_LOADING';
export const CLEAR_EXPENSES ='CLEAR_EXPENSES';

export const GET_GROUPS_DETAILS ='GET_GROUPS_DETAILS';
export const GROUPS_LOADING ='GROUPS_LOADING';
export const CLEAR_GROUPS ='CLEAR_GROUPS'; 

export const GET_ALL_GROUPS ='GET_ALL_GROUPS';
export const GET_ALL_USERS ='GET_ALL_USERS';
export const GET_GROUP_USERS_DETAILS ='GET_GROUP_USERS_DETAILS';

export const USER_LOGOUT ='USER_LOGOUT';
// export const GET_ALL_HOMES = 'GET_ALL_HOMES';
// export const GET_OWNER_HOMES = 'GET_OWNER_HOMES';
// export const OWNER_HOME_LOADING = 'OWNER_HOME_LOADING';
// export const GET_HOME= 'GET_HOME';
// export const BOOK_HOME= 'BOOK_HOME';
// export const GET_BOOKED_HOMES = 'GET_BOOKED_HOMES';